
number={"1":"CWE CATEGORY: DEPRECATED: Location",
"2":"CWE CATEGORY: 7PK - Environment",
"3":"CWE CATEGORY: DEPRECATED: Technology-specific Environment Issues",
"4":"CWE CATEGORY: J2EE Environment Issues",
"5":"CWE-5: J2EE Misconfiguration: Data Transmission Without Encryption",
"6":"CWE-6: J2EE Misconfiguration: Insufficient Session-ID Length",
"7":"CWE-7: J2EE Misconfiguration: Missing Custom Error Page",
"8":"CWE-8: J2EE Misconfiguration: Entity Bean Declared Remote",
"9":"CWE-9: J2EE Misconfiguration: Weak Access Permissions for EJB Methods",
"10":"CWE CATEGORY: DEPRECATED: ASP.NET Environment Issues",
"11":"CWE-11: ASP.NET Misconfiguration: Creating Debug Binary",
"12":"CWE-12: ASP.NET Misconfiguration: Missing Custom Error Page",
"13":"CWE-13: ASP.NET Misconfiguration: Password in Configuration File",
"14":"CWE-14: Compiler Removal of Code to Clear Buffers",
"15":"CWE-15: External Control of System or Configuration Setting",
"16":"CWE CATEGORY: Configuration",
"17":"CWE CATEGORY: DEPRECATED: Code",
"18":"CWE CATEGORY: DEPRECATED: Source Code",
"19":"CWE CATEGORY: Data Processing Errors",
"20":"CWE-20: Improper Input Validation",
"21":"CWE CATEGORY: Pathname Traversal and Equivalence Errors",
"22":"CWE-22: Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
"23":"CWE-23: Relative Path Traversal",
"24":"CWE-24: Path Traversal: '../filedir'",
"25":"CWE-25: Path Traversal: '/../filedir'",
"26":"CWE-26: Path Traversal: '/dir/../filename'",
"27":"CWE-27: Path Traversal: 'dir/../../filename'",
"28":"CWE-28: Path Traversal: '..\filedir'",
"29":"CWE-29: Path Traversal: '\..\filename'",
"30":"CWE-30: Path Traversal: '\dir\..\filename'",
"31":"CWE-31: Path Traversal: 'dir\..\..\filename'",
"32":"CWE-32: Path Traversal: '...' (Triple Dot)",
"33":"CWE-33: Path Traversal: '....' (Multiple Dot)",
"34":"CWE-34: Path Traversal: '....//'",
"35":"CWE-35: Path Traversal: '.../...//'",
"36":"CWE-36: Absolute Path Traversal",
"37":"CWE-37: Path Traversal: '/absolute/pathname/here'",
"38":"CWE-38: Path Traversal: '\absolute\pathname\here'",
"39":"CWE-39: Path Traversal: 'C:dirname'",
"40":"CWE-40: Path Traversal: '\\UNC\share\name\' (Windows UNC Share)",
"41":"CWE-41: Improper Resolution of Path Equivalence",
"42":"CWE-42: Path Equivalence: 'filename.' (Trailing Dot)",
"43":"CWE-43: Path Equivalence: 'filename....' (Multiple Trailing Dot)",
"44":"CWE-44: Path Equivalence: 'file.name' (Internal Dot)",
"45":"CWE-45: Path Equivalence: 'file...name' (Multiple Internal Dot)",
"46":"CWE-46: Path Equivalence: 'filename ' (Trailing Space)",
"47":"CWE-47: Path Equivalence: ' filename' (Leading Space)",
"48":"CWE-48: Path Equivalence: 'file name' (Internal Whitespace)",
"49":"CWE-49: Path Equivalence: 'filename/' (Trailing Slash)",
"50":"CWE-50: Path Equivalence: '//multiple/leading/slash'",
"51":"CWE-51: Path Equivalence: '/multiple//internal/slash'",
"52":"CWE-52: Path Equivalence: '/multiple/trailing/slash//'",
"53":"CWE-53: Path Equivalence: '\multiple\\internal\backslash'",
"54":"CWE-54: Path Equivalence: 'filedir\' (Trailing Backslash)",
"55":"CWE-55: Path Equivalence: '/./' (Single Dot Directory)",
"56":"CWE-56: Path Equivalence: 'filedir*' (Wildcard)",
"57":"CWE-57: Path Equivalence: 'fakedir/../realdir/filename'",
"58":"CWE-58: Path Equivalence: Windows 8.3 Filename",
"59":"CWE-59: Improper Link Resolution Before File Access ('Link Following')",
"60":"CWE CATEGORY: DEPRECATED: UNIX Path Link Problems",
"61":"CWE-61: UNIX Symbolic Link (Symlink) Following",
"62":"CWE-62: UNIX Hard Link",
"63":"CWE CATEGORY: DEPRECATED: Windows Path Link Problems",
"64":"CWE-64: Windows Shortcut Following (.LNK)",
"65":"CWE-65: Windows Hard Link",
"66":"CWE-66: Improper Handling of File Names that Identify Virtual Resources",
"67":"CWE-67: Improper Handling of Windows Device Names",
"68":"CWE CATEGORY: DEPRECATED: Windows Virtual File Problems",
"69":"CWE-69: Improper Handling of Windows ::DATA Alternate Data Stream",
"70":"CWE CATEGORY: DEPRECATED: Mac Virtual File Problems",
"71":"CWE-71: DEPRECATED: Apple '.DS_Store'",
"72":"CWE-72: Improper Handling of Apple HFS+ Alternate Data Stream Path",
"73":"CWE-73: External Control of File Name or Path",
"74":"CWE-74: Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')",
"75":"CWE-75: Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)",
"76":"CWE-76: Improper Neutralization of Equivalent Special Elements",
"77":"CWE-77: Improper Neutralization of Special Elements used in a Command ('Command Injection')",
"78":"CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
"79":"CWE-79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
"80":"CWE-80: Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)",
"81":"CWE-81: Improper Neutralization of Script in an Error Message Web Page",
"82":"CWE-82: Improper Neutralization of Script in Attributes of IMG Tags in a Web Page",
"83":"CWE-83: Improper Neutralization of Script in Attributes in a Web Page",
"84":"CWE-84: Improper Neutralization of Encoded URI Schemes in a Web Page",
"85":"CWE-85: Doubled Character XSS Manipulations",
"86":"CWE-86: Improper Neutralization of Invalid Characters in Identifiers in Web Pages",
"87":"CWE-87: Improper Neutralization of Alternate XSS Syntax",
"88":"CWE-88: Argument Injection or Modification",
"89":"CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
"90":"CWE-90: Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')",
"91":"CWE-91: XML Injection (aka Blind XPath Injection)",
"92":"CWE-92: DEPRECATED: Improper Sanitization of Custom Special Characters",
"93":"CWE-93: Improper Neutralization of CRLF Sequences ('CRLF Injection')",
"94":"CWE-94: Improper Control of Generation of Code ('Code Injection')",
"95":"CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')",
"96":"CWE-96: Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')",
"97":"CWE-97: Improper Neutralization of Server-Side Includes (SSI) Within a Web Page",
"98":"CWE-98: Improper Control of Filename for Include/Require Statement in PHP Program ('PHP Remote File Inclusion')",
"99":"CWE-99: Improper Control of Resource Identifiers ('Resource Injection')",
"100":"CWE CATEGORY: DEPRECATED: Technology-Specific Input Validation Problems",
"101":"CWE CATEGORY: DEPRECATED: Struts Validation Problems",
"102":"CWE-102: Struts: Duplicate Validation Forms",
"103":"CWE-103: Struts: Incomplete validate() Method Definition",
"104":"CWE-104: Struts: Form Bean Does Not Extend Validation Class",
"105":"CWE-105: Struts: Form Field Without Validator",
"106":"CWE-106: Struts: Plug-in Framework not in Use",
"107":"CWE-107: Struts: Unused Validation Form",
"108":"CWE-108: Struts: Unvalidated Action Form",
"109":"CWE-109: Struts: Validator Turned Off",
"110":"CWE-110: Struts: Validator Without Form Field",
"111":"CWE-111: Direct Use of Unsafe JNI",
"112":"CWE-112: Missing XML Validation",
"113":"CWE-113: Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Response Splitting')",
"114":"CWE-114: Process Control",
"115":"CWE-115: Misinterpretation of Input",
"116":"CWE-116: Improper Encoding or Escaping of Output",
"117":"CWE-117: Improper Output Neutralization for Logs",
"118":"CWE-118: Incorrect Access of Indexable Resource ('Range Error')",
"119":"CWE-119: Improper Restriction of Operations within the Bounds of a Memory Buffer",
"120":"CWE-120: Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')",
"121":"CWE-121: Stack-based Buffer Overflow",
"122":"CWE-122: Heap-based Buffer Overflow",
"123":"CWE-123: Write-what-where Condition",
"124":"CWE-124: Buffer Underwrite ('Buffer Underflow')",
"125":"CWE-125: Out-of-bounds Read",
"126":"CWE-126: Buffer Over-read",
"127":"CWE-127: Buffer Under-read",
"128":"CWE-128: Wrap-around Error",
"129":"CWE-129: Improper Validation of Array Index",
"130":"CWE-130: Improper Handling of Length Parameter Inconsistency ",
"131":"CWE-131: Incorrect Calculation of Buffer Size",
"132":"CWE-132: DEPRECATED (Duplicate): Miscalculated Null Termination",
"133":"CWE CATEGORY: String Errors",
"134":"CWE-134: Use of Externally-Controlled Format String",
"135":"CWE-135: Incorrect Calculation of Multi-Byte String Length",
"136":"CWE CATEGORY: Type Errors",
"137":"CWE CATEGORY: Representation Errors",
"138":"CWE-138: Improper Neutralization of Special Elements",
"139":"CWE CATEGORY: DEPRECATED: General Special Element Problems",
"140":"CWE-140: Improper Neutralization of Delimiters",
"141":"CWE-141: Improper Neutralization of Parameter/Argument Delimiters",
"142":"CWE-142: Improper Neutralization of Value Delimiters",
"143":"CWE-143: Improper Neutralization of Record Delimiters",
"144":"CWE-144: Improper Neutralization of Line Delimiters",
"145":"CWE-145: Improper Neutralization of Section Delimiters",
"146":"CWE-146: Improper Neutralization of Expression/Command Delimiters",
"147":"CWE-147: Improper Neutralization of Input Terminators",
"148":"CWE-148: Improper Neutralization of Input Leaders",
"149":"CWE-149: Improper Neutralization of Quoting Syntax",
"150":"CWE-150: Improper Neutralization of Escape, Meta, or Control Sequences",
"151":"CWE-151: Improper Neutralization of Comment Delimiters",
"152":"CWE-152: Improper Neutralization of Macro Symbols",
"153":"CWE-153: Improper Neutralization of Substitution Characters",
"154":"CWE-154: Improper Neutralization of Variable Name Delimiters",
"155":"CWE-155: Improper Neutralization of Wildcards or Matching Symbols",
"156":"CWE-156: Improper Neutralization of Whitespace",
"157":"CWE-157: Failure to Sanitize Paired Delimiters",
"158":"CWE-158: Improper Neutralization of Null Byte or NUL Character",
"159":"CWE-159: Failure to Sanitize Special Element",
"160":"CWE-160: Improper Neutralization of Leading Special Elements",
"161":"CWE-161: Improper Neutralization of Multiple Leading Special Elements",
"162":"CWE-162: Improper Neutralization of Trailing Special Elements",
"163":"CWE-163: Improper Neutralization of Multiple Trailing Special Elements",
"164":"CWE-164: Improper Neutralization of Internal Special Elements",
"165":"CWE-165: Improper Neutralization of Multiple Internal Special Elements",
"166":"CWE-166: Improper Handling of Missing Special Element",
"167":"CWE-167: Improper Handling of Additional Special Element",
"168":"CWE-168: Improper Handling of Inconsistent Special Elements",
"169":"CWE CATEGORY: DEPRECATED: Technology-Specific Special Elements",
"170":"CWE-170: Improper Null Termination",
"171":"CWE CATEGORY: Cleansing, Canonicalization, and Comparison Errors",
"172":"CWE-172: Encoding Error",
"173":"CWE-173: Improper Handling of Alternate Encoding",
"174":"CWE-174: Double Decoding of the Same Data",
"175":"CWE-175: Improper Handling of Mixed Encoding",
"176":"CWE-176: Improper Handling of Unicode Encoding",
"177":"CWE-177: Improper Handling of URL Encoding (Hex Encoding)",
"178":"CWE-178: Improper Handling of Case Sensitivity",
"179":"CWE-179: Incorrect Behavior Order: Early Validation",
"180":"CWE-180: Incorrect Behavior Order: Validate Before Canonicalize",
"181":"CWE-181: Incorrect Behavior Order: Validate Before Filter",
"182":"CWE-182: Collapse of Data into Unsafe Value",
"183":"CWE-183: Permissive Whitelist",
"184":"CWE-184: Incomplete Blacklist",
"185":"CWE-185: Incorrect Regular Expression",
"186":"CWE-186: Overly Restrictive Regular Expression",
"187":"CWE-187: Partial String Comparison",
"188":"CWE-188: Reliance on Data/Memory Layout",
"189":"CWE CATEGORY: Numeric Errors",
"190":"CWE-190: Integer Overflow or Wraparound",
"191":"CWE-191: Integer Underflow (Wrap or Wraparound)",
"192":"CWE-192: Integer Coercion Error",
"193":"CWE-193: Off-by-one Error",
"194":"CWE-194: Unexpected Sign Extension",
"195":"CWE-195: Signed to Unsigned Conversion Error",
"196":"CWE-196: Unsigned to Signed Conversion Error",
"197":"CWE-197: Numeric Truncation Error",
"198":"CWE-198: Use of Incorrect Byte Ordering",
"199":"CWE CATEGORY: Information Management Errors",
"200":"CWE-200: Information Exposure",
"201":"CWE-201: Information Exposure Through Sent Data",
"202":"CWE-202: Exposure of Sensitive Data Through Data Queries",
"203":"CWE-203: Information Exposure Through Discrepancy",
"204":"CWE-204: Response Discrepancy Information Exposure",
"205":"CWE-205: Information Exposure Through Behavioral Discrepancy",
"206":"CWE-206: Information Exposure of Internal State Through Behavioral Inconsistency",
"207":"CWE-207: Information Exposure Through an External Behavioral Inconsistency",
"208":"CWE-208: Information Exposure Through Timing Discrepancy",
"209":"CWE-209: Information Exposure Through an Error Message",
"210":"CWE-210: Information Exposure Through Self-generated Error Message",
"211":"CWE-211: Information Exposure Through Externally-Generated Error Message",
"212":"CWE-212: Improper Cross-boundary Removal of Sensitive Data",
"213":"CWE-213: Intentional Information Exposure",
"214":"CWE-214: Information Exposure Through Process Environment",
"215":"CWE-215: Information Exposure Through Debug Information",
"216":"CWE-216: Containment Errors (Container Errors)",
"217":"CWE-217: DEPRECATED: Failure to Protect Stored Data from Modification",
"218":"CWE-218: DEPRECATED (Duplicate): Failure to provide confidentiality for stored data",
"219":"CWE-219: Sensitive Data Under Web Root",
"220":"CWE-220: Sensitive Data Under FTP Root",
"221":"CWE-221: Information Loss or Omission",
"222":"CWE-222: Truncation of Security-relevant Information",
"223":"CWE-223: Omission of Security-relevant Information",
"224":"CWE-224: Obscured Security-relevant Information by Alternate Name",
"225":"CWE-225: DEPRECATED (Duplicate): General Information Management Problems",
"226":"CWE-226: Sensitive Information Uncleared Before Release",
"227":"CWE CATEGORY: 7PK - API Abuse",
"228":"CWE-228: Improper Handling of Syntactically Invalid Structure",
"229":"CWE-229: Improper Handling of Values",
"230":"CWE-230: Improper Handling of Missing Values",
"231":"CWE-231: Improper Handling of Extra Values",
"232":"CWE-232: Improper Handling of Undefined Values",
"233":"CWE-233: Improper Handling of Parameters",
"234":"CWE-234: Failure to Handle Missing Parameter",
"235":"CWE-235: Improper Handling of Extra Parameters",
"236":"CWE-236: Improper Handling of Undefined Parameters",
"237":"CWE-237: Improper Handling of Structural Elements",
"238":"CWE-238: Improper Handling of Incomplete Structural Elements",
"239":"CWE-239: Failure to Handle Incomplete Element",
"240":"CWE-240: Improper Handling of Inconsistent Structural Elements",
"241":"CWE-241: Improper Handling of Unexpected Data Type",
"242":"CWE-242: Use of Inherently Dangerous Function",
"243":"CWE-243: Creation of chroot Jail Without Changing Working Directory",
"244":"CWE-244: Improper Clearing of Heap Memory Before Release ('Heap Inspection')",
"245":"CWE-245: J2EE Bad Practices: Direct Management of Connections",
"246":"CWE-246: J2EE Bad Practices: Direct Use of Sockets",
"247":"CWE-247: DEPRECATED (Duplicate): Reliance on DNS Lookups in a Security Decision",
"248":"CWE-248: Uncaught Exception",
"249":"CWE-249: DEPRECATED: Often Misused: Path Manipulation",
"250":"CWE-250: Execution with Unnecessary Privileges",
"251":"CWE CATEGORY: Often Misused: String Management",
"252":"CWE-252: Unchecked Return Value",
"253":"CWE-253: Incorrect Check of Function Return Value",
"254":"CWE CATEGORY: 7PK - Security Features",
"255":"CWE CATEGORY: Credentials Management",
"256":"CWE-256: Unprotected Storage of Credentials",
"257":"CWE-257: Storing Passwords in a Recoverable Format",
"258":"CWE-258: Empty Password in Configuration File",
"259":"CWE-259: Use of Hard-coded Password",
"260":"CWE-260: Password in Configuration File",
"261":"CWE-261: Weak Cryptography for Passwords",
"262":"CWE-262: Not Using Password Aging",
"263":"CWE-263: Password Aging with Long Expiration",
"264":"CWE CATEGORY: Permissions, Privileges, and Access Controls",
"265":"CWE CATEGORY: Privilege / Sandbox Issues",
"266":"CWE-266: Incorrect Privilege Assignment",
"267":"CWE-267: Privilege Defined With Unsafe Actions",
"268":"CWE-268: Privilege Chaining",
"269":"CWE-269: Improper Privilege Management",
"270":"CWE-270: Privilege Context Switching Error",
"271":"CWE-271: Privilege Dropping / Lowering Errors",
"272":"CWE-272: Least Privilege Violation",
"273":"CWE-273: Improper Check for Dropped Privileges",
"274":"CWE-274: Improper Handling of Insufficient Privileges",
"275":"CWE CATEGORY: Permission Issues",
"276":"CWE-276: Incorrect Default Permissions",
"277":"CWE-277: Insecure Inherited Permissions",
"278":"CWE-278: Insecure Preserved Inherited Permissions",
"279":"CWE-279: Incorrect Execution-Assigned Permissions",
"280":"CWE-280: Improper Handling of Insufficient Permissions or Privileges ",
"281":"CWE-281: Improper Preservation of Permissions",
"282":"CWE-282: Improper Ownership Management",
"283":"CWE-283: Unverified Ownership",
"284":"CWE-284: Improper Access Control",
"285":"CWE-285: Improper Authorization",
"286":"CWE-286: Incorrect User Management",
"287":"CWE-287: Improper Authentication",
"288":"CWE-288: Authentication Bypass Using an Alternate Path or Channel",
"289":"CWE-289: Authentication Bypass by Alternate Name",
"290":"CWE-290: Authentication Bypass by Spoofing",
"291":"CWE-291: Reliance on IP Address for Authentication",
"292":"CWE-292: DEPRECATED (Duplicate): Trusting Self-reported DNS Name",
"293":"CWE-293: Using Referer Field for Authentication",
"294":"CWE-294: Authentication Bypass by Capture-replay",
"295":"CWE-295: Improper Certificate Validation",
"296":"CWE-296: Improper Following of a Certificate's Chain of Trust",
"297":"CWE-297: Improper Validation of Certificate with Host Mismatch",
"298":"CWE-298: Improper Validation of Certificate Expiration",
"299":"CWE-299: Improper Check for Certificate Revocation",
"300":"CWE-300: Channel Accessible by Non-Endpoint ('Man-in-the-Middle')",
"301":"CWE-301: Reflection Attack in an Authentication Protocol",
"302":"CWE-302: Authentication Bypass by Assumed-Immutable Data",
"303":"CWE-303: Incorrect Implementation of Authentication Algorithm",
"304":"CWE-304: Missing Critical Step in Authentication",
"305":"CWE-305: Authentication Bypass by Primary Weakness",
"306":"CWE-306: Missing Authentication for Critical Function",
"307":"CWE-307: Improper Restriction of Excessive Authentication Attempts",
"308":"CWE-308: Use of Single-factor Authentication",
"309":"CWE-309: Use of Password System for Primary Authentication",
"310":"CWE CATEGORY: Cryptographic Issues",
"311":"CWE-311: Missing Encryption of Sensitive Data",
"312":"CWE-312: Cleartext Storage of Sensitive Information",
"313":"CWE-313: Cleartext Storage in a File or on Disk",
"314":"CWE-314: Cleartext Storage in the Registry",
"315":"CWE-315: Cleartext Storage of Sensitive Information in a Cookie",
"316":"CWE-316: Cleartext Storage of Sensitive Information in Memory",
"317":"CWE-317: Cleartext Storage of Sensitive Information in GUI",
"318":"CWE-318: Cleartext Storage of Sensitive Information in Executable",
"319":"CWE-319: Cleartext Transmission of Sensitive Information",
"320":"CWE CATEGORY: Key Management Errors",
"321":"CWE-321: Use of Hard-coded Cryptographic Key",
"322":"CWE-322: Key Exchange without Entity Authentication",
"323":"CWE-323: Reusing a Nonce, Key Pair in Encryption",
"324":"CWE-324: Use of a Key Past its Expiration Date",
"325":"CWE-325: Missing Required Cryptographic Step",
"326":"CWE-326: Inadequate Encryption Strength",
"327":"CWE-327: Use of a Broken or Risky Cryptographic Algorithm",
"328":"CWE-328: Reversible One-Way Hash",
"329":"CWE-329: Not Using a Random IV with CBC Mode",
"330":"CWE-330: Use of Insufficiently Random Values",
"331":"CWE-331: Insufficient Entropy",
"332":"CWE-332: Insufficient Entropy in PRNG",
"333":"CWE-333: Improper Handling of Insufficient Entropy in TRNG",
"334":"CWE-334: Small Space of Random Values",
"335":"CWE-335: Incorrect Usage of Seeds in Pseudo-Random Number Generator (PRNG)",
"336":"CWE-336: Same Seed in Pseudo-Random Number Generator (PRNG)",
"337":"CWE-337: Predictable Seed in Pseudo-Random Number Generator (PRNG)",
"338":"CWE-338: Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)",
"339":"CWE-339: Small Seed Space in PRNG",
"340":"CWE-340: Predictability Problems",
"341":"CWE-341: Predictable from Observable State",
"342":"CWE-342: Predictable Exact Value from Previous Values",
"343":"CWE-343: Predictable Value Range from Previous Values",
"344":"CWE-344: Use of Invariant Value in Dynamically Changing Context",
"345":"CWE-345: Insufficient Verification of Data Authenticity",
"346":"CWE-346: Origin Validation Error",
"347":"CWE-347: Improper Verification of Cryptographic Signature",
"348":"CWE-348: Use of Less Trusted Source",
"349":"CWE-349: Acceptance of Extraneous Untrusted Data With Trusted Data",
"350":"CWE-350: Reliance on Reverse DNS Resolution for a Security-Critical Action",
"351":"CWE-351: Insufficient Type Distinction",
"352":"CWE-352: Cross-Site Request Forgery (CSRF)",
"353":"CWE-353: Missing Support for Integrity Check",
"354":"CWE-354: Improper Validation of Integrity Check Value",
"355":"CWE CATEGORY: User Interface Security Issues",
"356":"CWE-356: Product UI does not Warn User of Unsafe Actions",
"357":"CWE-357: Insufficient UI Warning of Dangerous Operations",
"358":"CWE-358: Improperly Implemented Security Check for Standard",
"359":"CWE-359: Exposure of Private Information ('Privacy Violation')",
"360":"CWE-360: Trust of System Event Data",
"361":"CWE CATEGORY: 7PK - Time and State",
"362":"CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
"363":"CWE-363: Race Condition Enabling Link Following",
"364":"CWE-364: Signal Handler Race Condition",
"365":"CWE-365: Race Condition in Switch",
"366":"CWE-366: Race Condition within a Thread",
"367":"CWE-367: Time-of-check Time-of-use (TOCTOU) Race Condition",
"368":"CWE-368: Context Switching Race Condition",
"369":"CWE-369: Divide By Zero",
"370":"CWE-370: Missing Check for Certificate Revocation after Initial Check",
"371":"CWE CATEGORY: State Issues",
"372":"CWE-372: Incomplete Internal State Distinction",
"373":"CWE-373: DEPRECATED: State Synchronization Error",
"374":"CWE-374: Passing Mutable Objects to an Untrusted Method",
"375":"CWE-375: Returning a Mutable Object to an Untrusted Caller",
"376":"CWE CATEGORY: Temporary File Issues",
"377":"CWE-377: Insecure Temporary File",
"378":"CWE-378: Creation of Temporary File With Insecure Permissions",
"379":"CWE-379: Creation of Temporary File in Directory with Incorrect Permissions",
"380":"CWE CATEGORY: Technology-Specific Time and State Issues",
"381":"CWE CATEGORY: J2EE Time and State Issues",
"382":"CWE-382: J2EE Bad Practices: Use of System.exit()",
"383":"CWE-383: J2EE Bad Practices: Direct Use of Threads",
"384":"CWE-384: Session Fixation",
"385":"CWE-385: Covert Timing Channel",
"386":"CWE-386: Symbolic Name not Mapping to Correct Object",
"387":"CWE CATEGORY: Signal Errors",
"388":"CWE CATEGORY: 7PK - Errors",
"389":"CWE CATEGORY: Error Conditions, Return Values, Status Codes",
"390":"CWE-390: Detection of Error Condition Without Action",
"391":"CWE-391: Unchecked Error Condition",
"392":"CWE-392: Missing Report of Error Condition",
"393":"CWE-393: Return of Wrong Status Code",
"394":"CWE-394: Unexpected Status Code or Return Value",
"395":"CWE-395: Use of NullPointerException Catch to Detect NULL Pointer Dereference",
"396":"CWE-396: Declaration of Catch for Generic Exception",
"397":"CWE-397: Declaration of Throws for Generic Exception",
"398":"CWE CATEGORY: 7PK - Code Quality",
"399":"CWE CATEGORY: Resource Management Errors",
"400":"CWE-400: Uncontrolled Resource Consumption",
"401":"CWE-401: Missing Release of Memory after Effective Lifetime",
"402":"CWE-402: Transmission of Private Resources into a New Sphere ('Resource Leak')",
"403":"CWE-403: Exposure of File Descriptor to Unintended Control Sphere ('File Descriptor Leak')",
"404":"CWE-404: Improper Resource Shutdown or Release",
"405":"CWE-405: Asymmetric Resource Consumption (Amplification)",
"406":"CWE-406: Insufficient Control of Network Message Volume (Network Amplification)",
"407":"CWE-407: Inefficient Algorithmic Complexity",
"408":"CWE-408: Incorrect Behavior Order: Early Amplification",
"409":"CWE-409: Improper Handling of Highly Compressed Data (Data Amplification)",
"410":"CWE-410: Insufficient Resource Pool",
"411":"CWE CATEGORY: Resource Locking Problems",
"412":"CWE-412: Unrestricted Externally Accessible Lock",
"413":"CWE-413: Improper Resource Locking",
"414":"CWE-414: Missing Lock Check",
"415":"CWE-415: Double Free",
"416":"CWE-416: Use After Free",
"417":"CWE CATEGORY: Channel and Path Errors",
"418":"CWE CATEGORY: DEPRECATED: Channel Errors",
"419":"CWE-419: Unprotected Primary Channel",
"420":"CWE-420: Unprotected Alternate Channel",
"421":"CWE-421: Race Condition During Access to Alternate Channel",
"422":"CWE-422: Unprotected Windows Messaging Channel ('Shatter')",
"423":"CWE-423: DEPRECATED (Duplicate): Proxied Trusted Channel",
"424":"CWE-424: Improper Protection of Alternate Path",
"425":"CWE-425: Direct Request ('Forced Browsing')",
"426":"CWE-426: Untrusted Search Path",
"427":"CWE-427: Uncontrolled Search Path Element",
"428":"CWE-428: Unquoted Search Path or Element",
"429":"CWE CATEGORY: Handler Errors",
"430":"CWE-430: Deployment of Wrong Handler",
"431":"CWE-431: Missing Handler",
"432":"CWE-432: Dangerous Signal Handler not Disabled During Sensitive Operations",
"433":"CWE-433: Unparsed Raw Web Content Delivery",
"434":"CWE-434: Unrestricted Upload of File with Dangerous Type",
"435":"CWE-435: Improper Interaction Between Multiple Correctly-Behaving Entities",
"436":"CWE-436: Interpretation Conflict",
"437":"CWE-437: Incomplete Model of Endpoint Features",
"438":"CWE CATEGORY: Behavioral Problems",
"439":"CWE-439: Behavioral Change in New Version or Environment",
"440":"CWE-440: Expected Behavior Violation",
"441":"CWE-441: Unintended Proxy or Intermediary ('Confused Deputy')",
"442":"CWE CATEGORY: Web Problems",
"443":"CWE-443: DEPRECATED (Duplicate): HTTP response splitting",
"444":"CWE-444: Inconsistent Interpretation of HTTP Requests ('HTTP Request Smuggling')",
"445":"CWE CATEGORY: DEPRECATED: User Interface Errors",
"446":"CWE-446: UI Discrepancy for Security Feature",
"447":"CWE-447: Unimplemented or Unsupported Feature in UI",
"448":"CWE-448: Obsolete Feature in UI",
"449":"CWE-449: The UI Performs the Wrong Action",
"450":"CWE-450: Multiple Interpretations of UI Input",
"451":"CWE-451: User Interface (UI) Misrepresentation of Critical Information",
"452":"CWE CATEGORY: Initialization and Cleanup Errors",
"453":"CWE-453: Insecure Default Variable Initialization",
"454":"CWE-454: External Initialization of Trusted Variables or Data Stores",
"455":"CWE-455: Non-exit on Failed Initialization",
"456":"CWE-456: Missing Initialization of a Variable",
"457":"CWE-457: Use of Uninitialized Variable",
"458":"CWE-458: DEPRECATED: Incorrect Initialization",
"459":"CWE-459: Incomplete Cleanup",
"460":"CWE-460: Improper Cleanup on Thrown Exception",
"461":"CWE CATEGORY: Data Structure Issues",
"462":"CWE-462: Duplicate Key in Associative List (Alist)",
"463":"CWE-463: Deletion of Data Structure Sentinel",
"464":"CWE-464: Addition of Data Structure Sentinel",
"465":"CWE CATEGORY: Pointer Issues",
"466":"CWE-466: Return of Pointer Value Outside of Expected Range",
"467":"CWE-467: Use of sizeof() on a Pointer Type",
"468":"CWE-468: Incorrect Pointer Scaling",
"469":"CWE-469: Use of Pointer Subtraction to Determine Size",
"470":"CWE-470: Use of Externally-Controlled Input to Select Classes or Code ('Unsafe Reflection')",
"471":"CWE-471: Modification of Assumed-Immutable Data (MAID)",
"472":"CWE-472: External Control of Assumed-Immutable Web Parameter",
"473":"CWE-473: PHP External Variable Modification",
"474":"CWE-474: Use of Function with Inconsistent Implementations",
"475":"CWE-475: Undefined Behavior for Input to API",
"476":"CWE-476: NULL Pointer Dereference",
"477":"CWE-477: Use of Obsolete Function",
"478":"CWE-478: Missing Default Case in Switch Statement",
"479":"CWE-479: Signal Handler Use of a Non-reentrant Function",
"480":"CWE-480: Use of Incorrect Operator",
"481":"CWE-481: Assigning instead of Comparing",
"482":"CWE-482: Comparing instead of Assigning",
"483":"CWE-483: Incorrect Block Delimitation",
"484":"CWE-484: Omitted Break Statement in Switch",
"485":"CWE CATEGORY: 7PK - Encapsulation",
"486":"CWE-486: Comparison of Classes by Name",
"487":"CWE-487: Reliance on Package-level Scope",
"488":"CWE-488: Exposure of Data Element to Wrong Session",
"489":"CWE-489: Leftover Debug Code",
"490":"CWE CATEGORY: Mobile Code Issues",
"491":"CWE-491: Public cloneable() Method Without Final ('Object Hijack')",
"492":"CWE-492: Use of Inner Class Containing Sensitive Data",
"493":"CWE-493: Critical Public Variable Without Final Modifier",
"494":"CWE-494: Download of Code Without Integrity Check",
"495":"CWE-495: Private Data Structure Returned From A Public Method",
"496":"CWE-496: Public Data Assigned to Private Array-Typed Field",
"497":"CWE-497: Exposure of System Data to an Unauthorized Control Sphere",
"498":"CWE-498: Cloneable Class Containing Sensitive Information",
"499":"CWE-499: Serializable Class Containing Sensitive Data",
"500":"CWE-500: Public Static Field Not Marked Final",
"501":"CWE-501: Trust Boundary Violation",
"502":"CWE-502: Deserialization of Untrusted Data",
"503":"CWE CATEGORY: DEPRECATED: Byte/Object Code",
"504":"CWE CATEGORY: DEPRECATED: Motivation/Intent",
"505":"CWE CATEGORY: DEPRECATED: Intentionally Introduced Weakness",
"506":"CWE-506: Embedded Malicious Code",
"507":"CWE-507: Trojan Horse",
"508":"CWE-508: Non-Replicating Malicious Code",
"509":"CWE-509: Replicating Malicious Code (Virus or Worm)",
"510":"CWE-510: Trapdoor",
"511":"CWE-511: Logic/Time Bomb",
"512":"CWE-512: Spyware",
"513":"CWE CATEGORY: DEPRECATED: Intentionally Introduced Nonmalicious Weakness",
"514":"CWE-514: Covert Channel",
"515":"CWE-515: Covert Storage Channel",
"516":"CWE-516: DEPRECATED (Duplicate): Covert Timing Channel",
"517":"CWE CATEGORY: DEPRECATED: Other Intentional, Nonmalicious Weakness",
"518":"CWE CATEGORY: DEPRECATED: Inadvertently Introduced Weakness",
"519":"CWE CATEGORY: .NET Environment Issues",
"520":"CWE-520: .NET Misconfiguration: Use of Impersonation",
"521":"CWE-521: Weak Password Requirements",
"522":"CWE-522: Insufficiently Protected Credentials",
"523":"CWE-523: Unprotected Transport of Credentials",
"524":"CWE-524: Information Exposure Through Caching",
"525":"CWE-525: Information Exposure Through Browser Caching",
"526":"CWE-526: Information Exposure Through Environmental Variables",
"527":"CWE-527: Exposure of CVS Repository to an Unauthorized Control Sphere",
"528":"CWE-528: Exposure of Core Dump File to an Unauthorized Control Sphere",
"529":"CWE-529: Exposure of Access Control List Files to an Unauthorized Control Sphere",
"530":"CWE-530: Exposure of Backup File to an Unauthorized Control Sphere",
"531":"CWE-531: Information Exposure Through Test Code",
"532":"CWE-532: Inclusion of Sensitive Information in Log Files",
"533":"CWE-533: DEPRECATED: Information Exposure Through Server Log Files",
"534":"CWE-534: DEPRECATED: Information Exposure Through Debug Log Files",
"535":"CWE-535: Information Exposure Through Shell Error Message",
"536":"CWE-536: Information Exposure Through Servlet Runtime Error Message",
"537":"CWE-537: Information Exposure Through Java Runtime Error Message",
"538":"CWE-538: File and Directory Information Exposure",
"539":"CWE-539: Information Exposure Through Persistent Cookies",
"540":"CWE-540: Information Exposure Through Source Code",
"541":"CWE-541: Information Exposure Through Include Source Code",
"542":"CWE-542: DEPRECATED: Information Exposure Through Cleanup Log Files",
"543":"CWE-543: Use of Singleton Pattern Without Synchronization in a Multithreaded Context",
"544":"CWE-544: Missing Standardized Error Handling Mechanism",
"545":"CWE-545: DEPRECATED: Use of Dynamic Class Loading",
"546":"CWE-546: Suspicious Comment",
"547":"CWE-547: Use of Hard-coded, Security-relevant Constants",
"548":"CWE-548: Information Exposure Through Directory Listing",
"549":"CWE-549: Missing Password Field Masking",
"550":"CWE-550: Information Exposure Through Server Error Message",
"551":"CWE-551: Incorrect Behavior Order: Authorization Before Parsing and Canonicalization",
"552":"CWE-552: Files or Directories Accessible to External Parties",
"553":"CWE-553: Command Shell in Externally Accessible Directory",
"554":"CWE-554: ASP.NET Misconfiguration: Not Using Input Validation Framework",
"555":"CWE-555: J2EE Misconfiguration: Plaintext Password in Configuration File",
"556":"CWE-556: ASP.NET Misconfiguration: Use of Identity Impersonation",
"557":"CWE CATEGORY: Concurrency Issues",
"558":"CWE-558: Use of getlogin() in Multithreaded Application",
"559":"CWE CATEGORY: Often Misused: Arguments and Parameters",
"560":"CWE-560: Use of umask() with chmod-style Argument",
"561":"CWE-561: Dead Code",
"562":"CWE-562: Return of Stack Variable Address",
"563":"CWE-563: Assignment to Variable without Use",
"564":"CWE-564: SQL Injection: Hibernate",
"565":"CWE-565: Reliance on Cookies without Validation and Integrity Checking",
"566":"CWE-566: Authorization Bypass Through User-Controlled SQL Primary Key",
"567":"CWE-567: Unsynchronized Access to Shared Data in a Multithreaded Context",
"568":"CWE-568: finalize() Method Without super.finalize()",
"569":"CWE CATEGORY: Expression Issues",
"570":"CWE-570: Expression is Always False",
"571":"CWE-571: Expression is Always True",
"572":"CWE-572: Call to Thread run() instead of start()",
"573":"CWE-573: Improper Following of Specification by Caller",
"574":"CWE-574: EJB Bad Practices: Use of Synchronization Primitives",
"575":"CWE-575: EJB Bad Practices: Use of AWT Swing",
"576":"CWE-576: EJB Bad Practices: Use of Java I/O",
"577":"CWE-577: EJB Bad Practices: Use of Sockets",
"578":"CWE-578: EJB Bad Practices: Use of Class Loader",
"579":"CWE-579: J2EE Bad Practices: Non-serializable Object Stored in Session",
"580":"CWE-580: clone() Method Without super.clone()",
"581":"CWE-581: Object Model Violation: Just One of Equals and Hashcode Defined",
"582":"CWE-582: Array Declared Public, Final, and Static",
"583":"CWE-583: finalize() Method Declared Public",
"584":"CWE-584: Return Inside Finally Block",
"585":"CWE-585: Empty Synchronized Block",
"586":"CWE-586: Explicit Call to Finalize()",
"587":"CWE-587: Assignment of a Fixed Address to a Pointer",
"588":"CWE-588: Attempt to Access Child of a Non-structure Pointer",
"589":"CWE-589: Call to Non-ubiquitous API",
"590":"CWE-590: Free of Memory not on the Heap",
"591":"CWE-591: Sensitive Data Storage in Improperly Locked Memory",
"592":"CWE-592: DEPRECATED: Authentication Bypass Issues",
"593":"CWE-593: Authentication Bypass: OpenSSL CTX Object Modified after SSL Objects are Created",
"594":"CWE-594: J2EE Framework: Saving Unserializable Objects to Disk",
"595":"CWE-595: Comparison of Object References Instead of Object Contents",
"596":"CWE-596: DEPRECATED: Incorrect Semantic Object Comparison",
"597":"CWE-597: Use of Wrong Operator in String Comparison",
"598":"CWE-598: Information Exposure Through Query Strings in GET Request",
"599":"CWE-599: Missing Validation of OpenSSL Certificate",
"600":"CWE-600: Uncaught Exception in Servlet ",
"601":"CWE-601: URL Redirection to Untrusted Site ('Open Redirect')",
"602":"CWE-602: Client-Side Enforcement of Server-Side Security",
"603":"CWE-603: Use of Client-Side Authentication",
"604":"CWE VIEW: Deprecated Entries",
"605":"CWE-605: Multiple Binds to the Same Port",
"606":"CWE-606: Unchecked Input for Loop Condition",
"607":"CWE-607: Public Static Final Field References Mutable Object",
"608":"CWE-608: Struts: Non-private Field in ActionForm Class",
"609":"CWE-609: Double-Checked Locking",
"610":"CWE-610: Externally Controlled Reference to a Resource in Another Sphere",
"611":"CWE-611: Improper Restriction of XML External Entity Reference",
"612":"CWE-612: Information Exposure Through Indexing of Private Data",
"613":"CWE-613: Insufficient Session Expiration",
"614":"CWE-614: Sensitive Cookie in HTTPS Session Without 'Secure' Attribute",
"615":"CWE-615: Information Exposure Through Comments",
"616":"CWE-616: Incomplete Identification of Uploaded File Variables (PHP)",
"617":"CWE-617: Reachable Assertion",
"618":"CWE-618: Exposed Unsafe ActiveX Method",
"619":"CWE-619: Dangling Database Cursor ('Cursor Injection')",
"620":"CWE-620: Unverified Password Change",
"621":"CWE-621: Variable Extraction Error",
"622":"CWE-622: Improper Validation of Function Hook Arguments",
"623":"CWE-623: Unsafe ActiveX Control Marked Safe For Scripting",
"624":"CWE-624: Executable Regular Expression Error",
"625":"CWE-625: Permissive Regular Expression",
"626":"CWE-626: Null Byte Interaction Error (Poison Null Byte)",
"627":"CWE-627: Dynamic Variable Evaluation",
"628":"CWE-628: Function Call with Incorrectly Specified Arguments",
"629":"CWE VIEW: Weaknesses in OWASP Top Ten (2007)",
"630":"CWE VIEW: DEPRECATED: Weaknesses Examined by SAMATE",
"631":"CWE VIEW: DEPRECATED: Resource-specific Weaknesses",
"632":"CWE CATEGORY: DEPRECATED: Weaknesses that Affect Files or Directories",
"633":"CWE CATEGORY: DEPRECATED: Weaknesses that Affect Memory",
"634":"CWE CATEGORY: DEPRECATED: Weaknesses that Affect System Processes",
"635":"CWE VIEW: Weaknesses Originally Used by NVD from 2008 to 2016",
"636":"CWE-636: Not Failing Securely ('Failing Open')",
"637":"CWE-637: Unnecessary Complexity in Protection Mechanism (Not Using 'Economy of Mechanism')",
"638":"CWE-638: Not Using Complete Mediation",
"639":"CWE-639: Authorization Bypass Through User-Controlled Key",
"640":"CWE-640: Weak Password Recovery Mechanism for Forgotten Password",
"641":"CWE-641: Improper Restriction of Names for Files and Other Resources",
"642":"CWE-642: External Control of Critical State Data",
"643":"CWE-643: Improper Neutralization of Data within XPath Expressions ('XPath Injection')",
"644":"CWE-644: Improper Neutralization of HTTP Headers for Scripting Syntax",
"645":"CWE-645: Overly Restrictive Account Lockout Mechanism",
"646":"CWE-646: Reliance on File Name or Extension of Externally-Supplied File",
"647":"CWE-647: Use of Non-Canonical URL Paths for Authorization Decisions",
"648":"CWE-648: Incorrect Use of Privileged APIs",
"649":"CWE-649: Reliance on Obfuscation or Encryption of Security-Relevant Inputs without Integrity Checking",
"650":"CWE-650: Trusting HTTP Permission Methods on the Server Side",
"651":"CWE-651: Information Exposure Through WSDL File",
"652":"CWE-652: Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')",
"653":"CWE-653: Insufficient Compartmentalization",
"654":"CWE-654: Reliance on a Single Factor in a Security Decision",
"655":"CWE-655: Insufficient Psychological Acceptability",
"656":"CWE-656: Reliance on Security Through Obscurity",
"657":"CWE-657: Violation of Secure Design Principles",
"658":"CWE VIEW: Weaknesses in Software Written in C",
"659":"CWE VIEW: Weaknesses in Software Written in C++",
"660":"CWE VIEW: Weaknesses in Software Written in Java",
"661":"CWE VIEW: Weaknesses in Software Written in PHP",
"662":"CWE-662: Improper Synchronization",
"663":"CWE-663: Use of a Non-reentrant Function in a Concurrent Context",
"664":"CWE-664: Improper Control of a Resource Through its Lifetime",
"665":"CWE-665: Improper Initialization",
"666":"CWE-666: Operation on Resource in Wrong Phase of Lifetime",
"667":"CWE-667: Improper Locking",
"668":"CWE-668: Exposure of Resource to Wrong Sphere",
"669":"CWE-669: Incorrect Resource Transfer Between Spheres",
"670":"CWE-670: Always-Incorrect Control Flow Implementation",
"671":"CWE-671: Lack of Administrator Control over Security",
"672":"CWE-672: Operation on a Resource after Expiration or Release",
"673":"CWE-673: External Influence of Sphere Definition",
"674":"CWE-674: Uncontrolled Recursion",
"675":"CWE-675: Duplicate Operations on Resource",
"676":"CWE-676: Use of Potentially Dangerous Function",
"677":"CWE VIEW: Weakness Base Elements",
"678":"CWE VIEW: Composites",
"679":"CWE VIEW: DEPRECATED: Chain Elements",
"680":"CWE-680: Integer Overflow to Buffer Overflow",
"681":"CWE-681: Incorrect Conversion between Numeric Types",
"682":"CWE-682: Incorrect Calculation",
"683":"CWE-683: Function Call With Incorrect Order of Arguments",
"684":"CWE-684: Incorrect Provision of Specified Functionality",
"685":"CWE-685: Function Call With Incorrect Number of Arguments",
"686":"CWE-686: Function Call With Incorrect Argument Type",
"687":"CWE-687: Function Call With Incorrectly Specified Argument Value",
"688":"CWE-688: Function Call With Incorrect Variable or Reference as Argument",
"689":"CWE-689: Permission Race Condition During Resource Copy",
"690":"CWE-690: Unchecked Return Value to NULL Pointer Dereference",
"691":"CWE-691: Insufficient Control Flow Management",
"692":"CWE-692: Incomplete Blacklist to Cross-Site Scripting",
"693":"CWE-693: Protection Mechanism Failure",
"694":"CWE-694: Use of Multiple Resources with Duplicate Identifier",
"695":"CWE-695: Use of Low-Level Functionality",
"696":"CWE-696: Incorrect Behavior Order",
"697":"CWE-697: Incorrect Comparison",
"698":"CWE-698: Execution After Redirect (EAR)",
"699":"CWE VIEW: Development Concepts",
"700":"CWE VIEW: Seven Pernicious Kingdoms",
"701":"CWE VIEW: Weaknesses Introduced During Design",
"702":"CWE VIEW: Weaknesses Introduced During Implementation",
"703":"CWE-703: Improper Check or Handling of Exceptional Conditions",
"704":"CWE-704: Incorrect Type Conversion or Cast",
"705":"CWE-705: Incorrect Control Flow Scoping",
"706":"CWE-706: Use of Incorrectly-Resolved Name or Reference",
"707":"CWE-707: Improper Enforcement of Message or Data Structure",
"708":"CWE-708: Incorrect Ownership Assignment",
"709":"CWE VIEW: Named Chains",
"710":"CWE-710: Improper Adherence to Coding Standards",
"711":"CWE VIEW: Weaknesses in OWASP Top Ten (2004)",
"712":"CWE CATEGORY: OWASP Top Ten 2007 Category A1 - Cross Site Scripting (XSS)",
"713":"CWE CATEGORY: OWASP Top Ten 2007 Category A2 - Injection Flaws",
"714":"CWE CATEGORY: OWASP Top Ten 2007 Category A3 - Malicious File Execution",
"715":"CWE CATEGORY: OWASP Top Ten 2007 Category A4 - Insecure Direct Object Reference",
"716":"CWE CATEGORY: OWASP Top Ten 2007 Category A5 - Cross Site Request Forgery (CSRF)",
"717":"CWE CATEGORY: OWASP Top Ten 2007 Category A6 - Information Leakage and Improper Error Handling",
"718":"CWE CATEGORY: OWASP Top Ten 2007 Category A7 - Broken Authentication and Session Management",
"719":"CWE CATEGORY: OWASP Top Ten 2007 Category A8 - Insecure Cryptographic Storage",
"720":"CWE CATEGORY: OWASP Top Ten 2007 Category A9 - Insecure Communications",
"721":"CWE CATEGORY: OWASP Top Ten 2007 Category A10 - Failure to Restrict URL Access",
"722":"CWE CATEGORY: OWASP Top Ten 2004 Category A1 - Unvalidated Input",
"723":"CWE CATEGORY: OWASP Top Ten 2004 Category A2 - Broken Access Control",
"724":"CWE CATEGORY: OWASP Top Ten 2004 Category A3 - Broken Authentication and Session Management",
"725":"CWE CATEGORY: OWASP Top Ten 2004 Category A4 - Cross-Site Scripting (XSS) Flaws",
"726":"CWE CATEGORY: OWASP Top Ten 2004 Category A5 - Buffer Overflows",
"727":"CWE CATEGORY: OWASP Top Ten 2004 Category A6 - Injection Flaws",
"728":"CWE CATEGORY: OWASP Top Ten 2004 Category A7 - Improper Error Handling",
"729":"CWE CATEGORY: OWASP Top Ten 2004 Category A8 - Insecure Storage",
"730":"CWE CATEGORY: OWASP Top Ten 2004 Category A9 - Denial of Service",
"731":"CWE CATEGORY: OWASP Top Ten 2004 Category A10 - Insecure Configuration Management",
"732":"CWE-732: Incorrect Permission Assignment for Critical Resource",
"733":"CWE-733: Compiler Optimization Removal or Modification of Security-critical Code",
"734":"CWE VIEW: Weaknesses Addressed by the CERT C Secure Coding Standard (2008)",
"735":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 2 - Preprocessor (PRE)",
"736":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 3 - Declarations and Initialization (DCL)",
"737":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 4 - Expressions (EXP)",
"738":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 5 - Integers (INT)",
"739":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 6 - Floating Point (FLP)",
"740":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 7 - Arrays (ARR)",
"741":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 8 - Characters and Strings (STR)",
"742":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 9 - Memory Management (MEM)",
"743":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 10 - Input Output (FIO)",
"744":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 11 - Environment (ENV)",
"745":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 12 - Signals (SIG)",
"746":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 13 - Error Handling (ERR)",
"747":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Chapter 14 - Miscellaneous (MSC)",
"748":"CWE CATEGORY: CERT C Secure Coding Standard (2008) Appendix - POSIX (POS)",
"749":"CWE-749: Exposed Dangerous Method or Function",
"750":"CWE VIEW: Weaknesses in the 2009 CWE/SANS Top 25 Most Dangerous Programming Errors",
"751":"CWE CATEGORY: 2009 Top 25 - Insecure Interaction Between Components",
"752":"CWE CATEGORY: 2009 Top 25 - Risky Resource Management",
"753":"CWE CATEGORY: 2009 Top 25 - Porous Defenses",
"754":"CWE-754: Improper Check for Unusual or Exceptional Conditions",
"755":"CWE-755: Improper Handling of Exceptional Conditions",
"756":"CWE-756: Missing Custom Error Page",
"757":"CWE-757: Selection of Less-Secure Algorithm During Negotiation ('Algorithm Downgrade')",
"758":"CWE-758: Reliance on Undefined, Unspecified, or Implementation-Defined Behavior",
"759":"CWE-759: Use of a One-Way Hash without a Salt",
"760":"CWE-760: Use of a One-Way Hash with a Predictable Salt",
"761":"CWE-761: Free of Pointer not at Start of Buffer",
"762":"CWE-762: Mismatched Memory Management Routines",
"763":"CWE-763: Release of Invalid Pointer or Reference",
"764":"CWE-764: Multiple Locks of a Critical Resource",
"765":"CWE-765: Multiple Unlocks of a Critical Resource",
"766":"CWE-766: Critical Data Element Declared Public",
"767":"CWE-767: Access to Critical Private Variable via Public Method",
"768":"CWE-768: Incorrect Short Circuit Evaluation",
"769":"CWE-769: DEPRECATED: Uncontrolled File Descriptor Consumption",
"770":"CWE-770: Allocation of Resources Without Limits or Throttling",
"771":"CWE-771: Missing Reference to Active Allocated Resource",
"772":"CWE-772: Missing Release of Resource after Effective Lifetime",
"773":"CWE-773: Missing Reference to Active File Descriptor or Handle",
"774":"CWE-774: Allocation of File Descriptors or Handles Without Limits or Throttling",
"775":"CWE-775: Missing Release of File Descriptor or Handle after Effective Lifetime",
"776":"CWE-776: Improper Restriction of Recursive Entity References in DTDs ('XML Entity Expansion')",
"777":"CWE-777: Regular Expression without Anchors",
"778":"CWE-778: Insufficient Logging",
"779":"CWE-779: Logging of Excessive Data",
"780":"CWE-780: Use of RSA Algorithm without OAEP",
"781":"CWE-781: Improper Address Validation in IOCTL with METHOD_NEITHER I/O Control Code",
"782":"CWE-782: Exposed IOCTL with Insufficient Access Control",
"783":"CWE-783: Operator Precedence Logic Error",
"784":"CWE-784: Reliance on Cookies without Validation and Integrity Checking in a Security Decision",
"785":"CWE-785: Use of Path Manipulation Function without Maximum-sized Buffer",
"786":"CWE-786: Access of Memory Location Before Start of Buffer",
"787":"CWE-787: Out-of-bounds Write",
"788":"CWE-788: Access of Memory Location After End of Buffer",
"789":"CWE-789: Uncontrolled Memory Allocation",
"790":"CWE-790: Improper Filtering of Special Elements",
"791":"CWE-791: Incomplete Filtering of Special Elements",
"792":"CWE-792: Incomplete Filtering of One or More Instances of Special Elements",
"793":"CWE-793: Only Filtering One Instance of a Special Element",
"794":"CWE-794: Incomplete Filtering of Multiple Instances of Special Elements",
"795":"CWE-795: Only Filtering Special Elements at a Specified Location",
"796":"CWE-796: Only Filtering Special Elements Relative to a Marker",
"797":"CWE-797: Only Filtering Special Elements at an Absolute Position",
"798":"CWE-798: Use of Hard-coded Credentials",
"799":"CWE-799: Improper Control of Interaction Frequency",
"800":"CWE VIEW: Weaknesses in the 2010 CWE/SANS Top 25 Most Dangerous Programming Errors",
"801":"CWE CATEGORY: 2010 Top 25 - Insecure Interaction Between Components",
"802":"CWE CATEGORY: 2010 Top 25 - Risky Resource Management",
"803":"CWE CATEGORY: 2010 Top 25 - Porous Defenses",
"804":"CWE-804: Guessable CAPTCHA",
"805":"CWE-805: Buffer Access with Incorrect Length Value",
"806":"CWE-806: Buffer Access Using Size of Source Buffer",
"807":"CWE-807: Reliance on Untrusted Inputs in a Security Decision",
"808":"CWE CATEGORY: 2010 Top 25 - Weaknesses On the Cusp",
"809":"CWE VIEW: Weaknesses in OWASP Top Ten (2010)",
"810":"CWE CATEGORY: OWASP Top Ten 2010 Category A1 - Injection",
"811":"CWE CATEGORY: OWASP Top Ten 2010 Category A2 - Cross-Site Scripting (XSS)",
"812":"CWE CATEGORY: OWASP Top Ten 2010 Category A3 - Broken Authentication and Session Management",
"813":"CWE CATEGORY: OWASP Top Ten 2010 Category A4 - Insecure Direct Object References",
"814":"CWE CATEGORY: OWASP Top Ten 2010 Category A5 - Cross-Site Request Forgery(CSRF)",
"815":"CWE CATEGORY: OWASP Top Ten 2010 Category A6 - Security Misconfiguration",
"816":"CWE CATEGORY: OWASP Top Ten 2010 Category A7 - Insecure Cryptographic Storage",
"817":"CWE CATEGORY: OWASP Top Ten 2010 Category A8 - Failure to Restrict URL Access",
"818":"CWE CATEGORY: OWASP Top Ten 2010 Category A9 - Insufficient Transport Layer Protection",
"819":"CWE CATEGORY: OWASP Top Ten 2010 Category A10 - Unvalidated Redirects and Forwards",
"820":"CWE-820: Missing Synchronization",
"821":"CWE-821: Incorrect Synchronization",
"822":"CWE-822: Untrusted Pointer Dereference",
"823":"CWE-823: Use of Out-of-range Pointer Offset",
"824":"CWE-824: Access of Uninitialized Pointer",
"825":"CWE-825: Expired Pointer Dereference",
"826":"CWE-826: Premature Release of Resource During Expected Lifetime",
"827":"CWE-827: Improper Control of Document Type Definition",
"828":"CWE-828: Signal Handler with Functionality that is not Asynchronous-Safe",
"829":"CWE-829: Inclusion of Functionality from Untrusted Control Sphere",
"830":"CWE-830: Inclusion of Web Functionality from an Untrusted Source",
"831":"CWE-831: Signal Handler Function Associated with Multiple Signals",
"832":"CWE-832: Unlock of a Resource that is not Locked",
"833":"CWE-833: Deadlock",
"834":"CWE-834: Excessive Iteration",
"835":"CWE-835: Loop with Unreachable Exit Condition ('Infinite Loop')",
"836":"CWE-836: Use of Password Hash Instead of Password for Authentication",
"837":"CWE-837: Improper Enforcement of a Single, Unique Action",
"838":"CWE-838: Inappropriate Encoding for Output Context",
"839":"CWE-839: Numeric Range Comparison Without Minimum Check",
"840":"CWE CATEGORY: Business Logic Errors",
"841":"CWE-841: Improper Enforcement of Behavioral Workflow",
"842":"CWE-842: Placement of User into Incorrect Group",
"843":"CWE-843: Access of Resource Using Incompatible Type ('Type Confusion')",
"844":"CWE VIEW: Weaknesses Addressed by The CERT Oracle Secure Coding Standard for Java (2011)",
"845":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 2 - Input Validation and Data Sanitization (IDS)",
"846":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 3 - Declarations and Initialization (DCL)",
"847":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 4 - Expressions (EXP)",
"848":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 5 - Numeric Types and Operations (NUM)",
"849":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 6 - Object Orientation (OBJ)",
"850":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 7 - Methods (MET)",
"851":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 8 - Exceptional Behavior (ERR)",
"852":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 9 - Visibility and Atomicity (VNA)",
"853":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 10 - Locking (LCK)",
"854":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 11 - Thread APIs (THI)",
"855":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 12 - Thread Pools (TPS)",
"856":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 13 - Thread-Safety Miscellaneous (TSM)",
"857":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 14 - Input Output (FIO)",
"858":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 15 - Serialization (SER)",
"859":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 16 - Platform Security (SEC)",
"860":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 17 - Runtime Environment (ENV)",
"861":"CWE CATEGORY: The CERT Oracle Secure Coding Standard for Java (2011) Chapter 18 - Miscellaneous (MSC)",
"862":"CWE-862: Missing Authorization",
"863":"CWE-863: Incorrect Authorization",
"864":"CWE CATEGORY: 2011 Top 25 - Insecure Interaction Between Components",
"865":"CWE CATEGORY: 2011 Top 25 - Risky Resource Management",
"866":"CWE CATEGORY: 2011 Top 25 - Porous Defenses",
"867":"CWE CATEGORY: 2011 Top 25 - Weaknesses On the Cusp",
"868":"CWE VIEW: Weaknesses Addressed by the SEI CERT C++ Coding Standard (2016 Version)",
"869":"CWE CATEGORY: CERT C++ Secure Coding Section 01 - Preprocessor (PRE)",
"870":"CWE CATEGORY: CERT C++ Secure Coding Section 02 - Declarations and Initialization (DCL)",
"871":"CWE CATEGORY: CERT C++ Secure Coding Section 03 - Expressions (EXP)",
"872":"CWE CATEGORY: CERT C++ Secure Coding Section 04 - Integers (INT)",
"873":"CWE CATEGORY: CERT C++ Secure Coding Section 05 - Floating Point Arithmetic (FLP)",
"874":"CWE CATEGORY: CERT C++ Secure Coding Section 06 - Arrays and the STL (ARR)",
"875":"CWE CATEGORY: CERT C++ Secure Coding Section 07 - Characters and Strings (STR)",
"876":"CWE CATEGORY: CERT C++ Secure Coding Section 08 - Memory Management (MEM)",
"877":"CWE CATEGORY: CERT C++ Secure Coding Section 09 - Input Output (FIO)",
"878":"CWE CATEGORY: CERT C++ Secure Coding Section 10 - Environment (ENV)",
"879":"CWE CATEGORY: CERT C++ Secure Coding Section 11 - Signals (SIG)",
"880":"CWE CATEGORY: CERT C++ Secure Coding Section 12 - Exceptions and Error Handling (ERR)",
"881":"CWE CATEGORY: CERT C++ Secure Coding Section 13 - Object Oriented Programming (OOP)",
"882":"CWE CATEGORY: CERT C++ Secure Coding Section 14 - Concurrency (CON)",
"883":"CWE CATEGORY: CERT C++ Secure Coding Section 49 - Miscellaneous (MSC)",
"884":"CWE VIEW: CWE Cross-section",
"885":"CWE CATEGORY: SFP Primary Cluster: Risky Values",
"886":"CWE CATEGORY: SFP Primary Cluster: Unused entities",
"887":"CWE CATEGORY: SFP Primary Cluster: API",
"888":"CWE VIEW: Software Fault Pattern (SFP) Clusters",
"889":"CWE CATEGORY: SFP Primary Cluster: Exception Management",
"890":"CWE CATEGORY: SFP Primary Cluster: Memory Access",
"891":"CWE CATEGORY: SFP Primary Cluster: Memory Management",
"892":"CWE CATEGORY: SFP Primary Cluster: Resource Management",
"893":"CWE CATEGORY: SFP Primary Cluster: Path Resolution",
"894":"CWE CATEGORY: SFP Primary Cluster: Synchronization",
"895":"CWE CATEGORY: SFP Primary Cluster: Information Leak",
"896":"CWE CATEGORY: SFP Primary Cluster: Tainted Input",
"897":"CWE CATEGORY: SFP Primary Cluster: Entry Points",
"898":"CWE CATEGORY: SFP Primary Cluster: Authentication",
"899":"CWE CATEGORY: SFP Primary Cluster: Access Control",
"900":"CWE VIEW: Weaknesses in the 2011 CWE/SANS Top 25 Most Dangerous Software Errors",
"901":"CWE CATEGORY: SFP Primary Cluster: Privilege",
"902":"CWE CATEGORY: SFP Primary Cluster: Channel",
"903":"CWE CATEGORY: SFP Primary Cluster: Cryptography",
"904":"CWE CATEGORY: SFP Primary Cluster: Malware",
"905":"CWE CATEGORY: SFP Primary Cluster: Predictability",
"906":"CWE CATEGORY: SFP Primary Cluster: UI",
"907":"CWE CATEGORY: SFP Primary Cluster: Other",
"908":"CWE-908: Use of Uninitialized Resource",
"909":"CWE-909: Missing Initialization of Resource",
"910":"CWE-910: Use of Expired File Descriptor",
"911":"CWE-911: Improper Update of Reference Count",
"912":"CWE-912: Hidden Functionality",
"913":"CWE-913: Improper Control of Dynamically-Managed Code Resources",
"914":"CWE-914: Improper Control of Dynamically-Identified Variables",
"915":"CWE-915: Improperly Controlled Modification of Dynamically-Determined Object Attributes",
"916":"CWE-916: Use of Password Hash With Insufficient Computational Effort",
"917":"CWE-917: Improper Neutralization of Special Elements used in an Expression Language Statement ('Expression Language Injection')",
"918":"CWE-918: Server-Side Request Forgery (SSRF)",
"919":"CWE VIEW: Weaknesses in Mobile Applications",
"920":"CWE-920: Improper Restriction of Power Consumption",
"921":"CWE-921: Storage of Sensitive Data in a Mechanism without Access Control",
"922":"CWE-922: Insecure Storage of Sensitive Information",
"923":"CWE-923: Improper Restriction of Communication Channel to Intended Endpoints",
"924":"CWE-924: Improper Enforcement of Message Integrity During Transmission in a Communication Channel",
"925":"CWE-925: Improper Verification of Intent by Broadcast Receiver",
"926":"CWE-926: Improper Export of Android Application Components",
"927":"CWE-927: Use of Implicit Intent for Sensitive Communication",
"928":"CWE VIEW: Weaknesses in OWASP Top Ten (2013)",
"929":"CWE CATEGORY: OWASP Top Ten 2013 Category A1 - Injection",
"930":"CWE CATEGORY: OWASP Top Ten 2013 Category A2 - Broken Authentication and Session Management",
"931":"CWE CATEGORY: OWASP Top Ten 2013 Category A3 - Cross-Site Scripting (XSS)",
"932":"CWE CATEGORY: OWASP Top Ten 2013 Category A4 - Insecure Direct Object References",
"933":"CWE CATEGORY: OWASP Top Ten 2013 Category A5 - Security Misconfiguration",
"934":"CWE CATEGORY: OWASP Top Ten 2013 Category A6 - Sensitive Data Exposure",
"935":"CWE CATEGORY: OWASP Top Ten 2013 Category A7 - Missing Function Level Access Control",
"936":"CWE CATEGORY: OWASP Top Ten 2013 Category A8 - Cross-Site Request Forgery (CSRF)",
"937":"CWE CATEGORY: OWASP Top Ten 2013 Category A9 - Using Components with Known Vulnerabilities",
"938":"CWE CATEGORY: OWASP Top Ten 2013 Category A10 - Unvalidated Redirects and Forwards",
"939":"CWE-939: Improper Authorization in Handler for Custom URL Scheme",
"940":"CWE-940: Improper Verification of Source of a Communication Channel",
"941":"CWE-941: Incorrectly Specified Destination in a Communication Channel",
"942":"CWE-942: Overly Permissive Cross-domain Whitelist",
"943":"CWE-943: Improper Neutralization of Special Elements in Data Query Logic",
"944":"CWE CATEGORY: SFP Secondary Cluster: Access Management",
"945":"CWE CATEGORY: SFP Secondary Cluster: Insecure Resource Access",
"946":"CWE CATEGORY: SFP Secondary Cluster: Insecure Resource Permissions",
"947":"CWE CATEGORY: SFP Secondary Cluster: Authentication Bypass",
"948":"CWE CATEGORY: SFP Secondary Cluster: Digital Certificate",
"949":"CWE CATEGORY: SFP Secondary Cluster: Faulty Endpoint Authentication",
"950":"CWE CATEGORY: SFP Secondary Cluster: Hardcoded Sensitive Data",
"951":"CWE CATEGORY: SFP Secondary Cluster: Insecure Authentication Policy",
"952":"CWE CATEGORY: SFP Secondary Cluster: Missing Authentication",
"953":"CWE CATEGORY: SFP Secondary Cluster: Missing Endpoint Authentication",
"954":"CWE CATEGORY: SFP Secondary Cluster: Multiple Binds to the Same Port",
"955":"CWE CATEGORY: SFP Secondary Cluster: Unrestricted Authentication",
"956":"CWE CATEGORY: SFP Secondary Cluster: Channel Attack",
"957":"CWE CATEGORY: SFP Secondary Cluster: Protocol Error",
"958":"CWE CATEGORY: SFP Secondary Cluster: Broken Cryptography",
"959":"CWE CATEGORY: SFP Secondary Cluster: Weak Cryptography",
"960":"CWE CATEGORY: SFP Secondary Cluster: Ambiguous Exception Type",
"961":"CWE CATEGORY: SFP Secondary Cluster: Incorrect Exception Behavior",
"962":"CWE CATEGORY: SFP Secondary Cluster: Unchecked Status Condition",
"963":"CWE CATEGORY: SFP Secondary Cluster: Exposed Data",
"964":"CWE CATEGORY: SFP Secondary Cluster: Exposure Temporary File",
"965":"CWE CATEGORY: SFP Secondary Cluster: Insecure Session Management",
"966":"CWE CATEGORY: SFP Secondary Cluster: Other Exposures",
"967":"CWE CATEGORY: SFP Secondary Cluster: State Disclosure",
"968":"CWE CATEGORY: SFP Secondary Cluster: Covert Channel",
"969":"CWE CATEGORY: SFP Secondary Cluster: Faulty Memory Release",
"970":"CWE CATEGORY: SFP Secondary Cluster: Faulty Buffer Access",
"971":"CWE CATEGORY: SFP Secondary Cluster: Faulty Pointer Use",
"972":"CWE CATEGORY: SFP Secondary Cluster: Faulty String Expansion",
"973":"CWE CATEGORY: SFP Secondary Cluster: Improper NULL Termination",
"974":"CWE CATEGORY: SFP Secondary Cluster: Incorrect Buffer Length Computation",
"975":"CWE CATEGORY: SFP Secondary Cluster: Architecture",
"976":"CWE CATEGORY: SFP Secondary Cluster: Compiler",
"977":"CWE CATEGORY: SFP Secondary Cluster: Design",
"978":"CWE CATEGORY: SFP Secondary Cluster: Implementation",
"979":"CWE CATEGORY: SFP Secondary Cluster: Failed Chroot Jail",
"980":"CWE CATEGORY: SFP Secondary Cluster: Link in Resource Name Resolution",
"981":"CWE CATEGORY: SFP Secondary Cluster: Path Traversal",
"982":"CWE CATEGORY: SFP Secondary Cluster: Failure to Release Resource",
"983":"CWE CATEGORY: SFP Secondary Cluster: Faulty Resource Use",
"984":"CWE CATEGORY: SFP Secondary Cluster: Life Cycle",
"985":"CWE CATEGORY: SFP Secondary Cluster: Unrestricted Consumption",
"986":"CWE CATEGORY: SFP Secondary Cluster: Missing Lock",
"987":"CWE CATEGORY: SFP Secondary Cluster: Multiple Locks/Unlocks",
"988":"CWE CATEGORY: SFP Secondary Cluster: Race Condition Window",
"989":"CWE CATEGORY: SFP Secondary Cluster: Unrestricted Lock",
"990":"CWE CATEGORY: SFP Secondary Cluster: Tainted Input to Command",
"991":"CWE CATEGORY: SFP Secondary Cluster: Tainted Input to Environment",
"992":"CWE CATEGORY: SFP Secondary Cluster: Faulty Input Transformation",
"993":"CWE CATEGORY: SFP Secondary Cluster: Incorrect Input Handling",
"994":"CWE CATEGORY: SFP Secondary Cluster: Tainted Input to Variable",
"995":"CWE CATEGORY: SFP Secondary Cluster: Feature",
"996":"CWE CATEGORY: SFP Secondary Cluster: Security",
"997":"CWE CATEGORY: SFP Secondary Cluster: Information Loss",
"998":"CWE CATEGORY: SFP Secondary Cluster: Glitch in Computation",
"999":"CWE VIEW: Weaknesses without Software Fault Patterns",
"1000":"CWE VIEW: Research Concepts",
"1001":"CWE CATEGORY: SFP Secondary Cluster: Use of an Improper API",
"1002":"CWE CATEGORY: SFP Secondary Cluster: Unexpected Entry Points",
"1003":"CWE VIEW: Weaknesses for Simplified Mapping of Published Vulnerabilities",
"1004":"CWE-1004: Sensitive Cookie Without 'HttpOnly' Flag",
"1005":"CWE CATEGORY: 7PK - Input Validation and Representation",
"1006":"CWE CATEGORY: Bad Coding Practices",
"1007":"CWE-1007: Insufficient Visual Distinction of Homoglyphs Presented to User",
"1008":"CWE VIEW: Architectural Concepts",
"1009":"CWE CATEGORY: Audit",
"1010":"CWE CATEGORY: Authenticate Actors",
"1011":"CWE CATEGORY: Authorize Actors",
"1012":"CWE CATEGORY: Cross Cutting",
"1013":"CWE CATEGORY: Encrypt Data",
"1014":"CWE CATEGORY: Identify Actors",
"1015":"CWE CATEGORY: Limit Access",
"1016":"CWE CATEGORY: Limit Exposure",
"1017":"CWE CATEGORY: Lock Computer",
"1018":"CWE CATEGORY: Manage User Sessions",
"1019":"CWE CATEGORY: Validate Inputs",
"1020":"CWE CATEGORY: Verify Message Integrity",
"1021":"CWE-1021: Improper Restriction of Rendered UI Layers or Frames",
"1022":"CWE-1022: Use of Web Link to Untrusted Target with window.opener Access",
"1023":"CWE-1023: Incomplete Comparison with Missing Factors",
"1024":"CWE-1024: Comparison of Incompatible Types",
"1025":"CWE-1025: Comparison Using Wrong Factors",
"1026":"CWE VIEW: Weaknesses in OWASP Top Ten (2017)",
"1027":"CWE CATEGORY: OWASP Top Ten 2017 Category A1 - Injection",
"1028":"CWE CATEGORY: OWASP Top Ten 2017 Category A2 - Broken Authentication",
"1029":"CWE CATEGORY: OWASP Top Ten 2017 Category A3 - Sensitive Data Exposure",
"1030":"CWE CATEGORY: OWASP Top Ten 2017 Category A4 - XML External Entities (XXE)",
"1031":"CWE CATEGORY: OWASP Top Ten 2017 Category A5 - Broken Access Control",
"1032":"CWE CATEGORY: OWASP Top Ten 2017 Category A6 - Security Misconfiguration",
"1033":"CWE CATEGORY: OWASP Top Ten 2017 Category A7 - Cross-Site Scripting (XSS)",
"1034":"CWE CATEGORY: OWASP Top Ten 2017 Category A8 - Insecure Deserialization",
"1035":"CWE CATEGORY: OWASP Top Ten 2017 Category A9 - Using Components with Known Vulnerabilities",
"1036":"CWE CATEGORY: OWASP Top Ten 2017 Category A10 - Insufficient Logging & Monitoring",
"1037":"CWE-1037: Processor Optimization Removal or Modification of Security-critical Code",
"1038":"CWE-1038: Insecure Automated Optimizations",
"1039":"CWE-1039: Automated Recognition Mechanism with Inadequate Detection or Handling of Adversarial Input Perturbations",
"1040":"CWE VIEW: Quality Weaknesses with Indirect Security Impacts",
"1041":"CWE-1041: Use of Redundant Code",
"1042":"CWE-1042: Static Member Data Element outside of a Singleton Class Element",
"1043":"CWE-1043: Data Element Aggregating an Excessively Large Number of Non-Primitive Elements",
"1044":"CWE-1044: Architecture with Number of Horizontal Layers Outside of Expected Range",
"1045":"CWE-1045: Parent Class with a Virtual Destructor and a Child Class without a Virtual Destructor",
"1046":"CWE-1046: Creation of Immutable Text Using String Concatenation",
"1047":"CWE-1047: Modules with Circular Dependencies",
"1048":"CWE-1048: Invokable Control Element with Large Number of Outward Calls",
"1049":"CWE-1049: Excessive Data Query Operations in a Large Data Table",
"1050":"CWE-1050: Excessive Platform Resource Consumption within a Loop",
"1051":"CWE-1051: Initialization with Hard-Coded Network Resource Configuration Data",
"1052":"CWE-1052: Excessive Use of Hard-Coded Literals in Initialization",
"1053":"CWE-1053: Missing Documentation for Design",
"1054":"CWE-1054: Invocation of a Control Element at an Unnecessarily Deep Horizontal Layer",
"1055":"CWE-1055: Multiple Inheritance from Concrete Classes",
"1056":"CWE-1056: Invokable Control Element with Variadic Parameters",
"1057":"CWE-1057: Data Access Operations Outside of Expected Data Manager Component",
"1058":"CWE-1058: Invokable Control Element in Multi-Thread Context with non-Final Static Storable or Member Element",
"1059":"CWE-1059: Incomplete Documentation",
"1060":"CWE-1060: Excessive Number of Inefficient Server-Side Data Accesses",
"1061":"CWE-1061: Insufficient Encapsulation",
"1062":"CWE-1062: Parent Class with References to Child Class",
"1063":"CWE-1063: Creation of Class Instance within a Static Code Block",
"1064":"CWE-1064: Invokable Control Element with Signature Containing an Excessive Number of Parameters",
"1065":"CWE-1065: Runtime Resource Management Control Element in a Component Built to Run on Application Servers",
"1066":"CWE-1066: Missing Serialization Control Element",
"1067":"CWE-1067: Excessive Execution of Sequential Searches of Data Resource",
"1068":"CWE-1068: Inconsistency Between Implementation and Documented Design",
"1069":"CWE-1069: Empty Exception Block",
"1070":"CWE-1070: Serializable Data Element Containing non-Serializable Item Elements",
"1071":"CWE-1071: Empty Code Block",
"1072":"CWE-1072: Data Resource Access without Use of Connection Pooling",
"1073":"CWE-1073: Non-SQL Invokable Control Element with Excessive Number of Data Resource Accesses",
"1074":"CWE-1074: Class with Excessively Deep Inheritance",
"1075":"CWE-1075: Unconditional Control Flow Transfer outside of Switch Block",
"1076":"CWE-1076: Insufficient Adherence to Expected Conventions",
"1077":"CWE-1077: Floating Point Comparison with Incorrect Operator",
"1078":"CWE-1078: Inappropriate Source Code Style or Formatting",
"1079":"CWE-1079: Parent Class without Virtual Destructor Method",
"1080":"CWE-1080: Source Code File with Excessive Number of Lines of Code",
"1082":"CWE-1082: Class Instance Self Destruction Control Element",
"1083":"CWE-1083: Data Access from Outside Expected Data Manager Component",
"1084":"CWE-1084: Invokable Control Element with Excessive File or Data Access Operations",
"1085":"CWE-1085: Invokable Control Element with Excessive Volume of Commented-out Code",
"1086":"CWE-1086: Class with Excessive Number of Child Classes",
"1087":"CWE-1087: Class with Virtual Method without a Virtual Destructor",
"1088":"CWE-1088: Synchronous Access of Remote Resource without Timeout",
"1089":"CWE-1089: Large Data Table with Excessive Number of Indices",
"1090":"CWE-1090: Method Containing Access of a Member Element from Another Class",
"1091":"CWE-1091: Use of Object without Invoking Destructor Method",
"1092":"CWE-1092: Use of Same Invokable Control Element in Multiple Architectural Layers",
"1093":"CWE-1093: Excessively Complex Data Representation",
"1094":"CWE-1094: Excessive Index Range Scan for a Data Resource",
"1095":"CWE-1095: Loop Condition Value Update within the Loop",
"1096":"CWE-1096: Singleton Class Instance Creation without Proper Locking or Synchronization",
"1097":"CWE-1097: Persistent Storable Data Element without Associated Comparison Control Element",
"1098":"CWE-1098: Data Element containing Pointer Item without Proper Copy Control Element",
"1099":"CWE-1099: Inconsistent Naming Conventions for Identifiers",
"1100":"CWE-1100: Insufficient Isolation of System-Dependent Functions",
"1101":"CWE-1101: Reliance on Runtime Component in Generated Code",
"1102":"CWE-1102: Reliance on Machine-Dependent Data Representation",
"1103":"CWE-1103: Use of Platform-Dependent Third Party Components",
"1104":"CWE-1104: Use of Unmaintained Third Party Components",
"1105":"CWE-1105: Insufficient Encapsulation of Machine-Dependent Functionality",
"1106":"CWE-1106: Insufficient Use of Symbolic Constants",
"1107":"CWE-1107: Insufficient Isolation of Symbolic Constant Definitions",
"1108":"CWE-1108: Excessive Reliance on Global Variables",
"1109":"CWE-1109: Use of Same Variable for Multiple Purposes",
"1110":"CWE-1110: Incomplete Design Documentation",
"1111":"CWE-1111: Incomplete I/O Documentation",
"1112":"CWE-1112: Incomplete Documentation of Program Execution",
"1113":"CWE-1113: Inappropriate Comment Style",
"1114":"CWE-1114: Inappropriate Whitespace Style",
"1115":"CWE-1115: Source Code Element without Standard Prologue",
"1116":"CWE-1116: Inaccurate Comments",
"1117":"CWE-1117: Callable with Insufficient Behavioral Summary",
"1118":"CWE-1118: Insufficient Documentation of Error Handling Techniques",
"1119":"CWE-1119: Excessive Use of Unconditional Branching",
"1120":"CWE-1120: Excessive Code Complexity",
"1121":"CWE-1121: Excessive McCabe Cyclomatic Complexity",
"1122":"CWE-1122: Excessive Halstead Complexity",
"1123":"CWE-1123: Excessive Use of Self-Modifying Code",
"1124":"CWE-1124: Excessively Deep Nesting",
"1125":"CWE-1125: Excessive Attack Surface",
"1126":"CWE-1126: Declaration of Variable with Unnecessarily Wide Scope",
"1127":"CWE-1127: Compilation with Insufficient Warnings or Errors",
"1128":"CWE VIEW: CISQ Quality Measures (2016)",
"1129":"CWE CATEGORY: CISQ Quality Measures - Reliability",
"1130":"CWE CATEGORY: CISQ Quality Measures - Maintainability",
"1131":"CWE CATEGORY: CISQ Quality Measures - Security",
"1132":"CWE CATEGORY: CISQ Quality Measures - Performance",
"1133":"CWE VIEW: Weaknesses Addressed by the SEI CERT Oracle Coding Standard for Java",
"1134":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 00. Input Validation and Data Sanitization (IDS)",
"1135":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 01. Declarations and Initialization (DCL)",
"1136":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 02. Expressions (EXP)",
"1137":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 03. Numeric Types and Operations (NUM)",
"1138":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 04. Characters and Strings (STR)",
"1139":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 05. Object Orientation (OBJ)",
"1140":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 06. Methods (MET)",
"1141":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 07. Exceptional Behavior (ERR)",
"1142":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 08. Visibility and Atomicity (VNA)",
"1143":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 09. Locking (LCK)",
"1144":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 10. Thread APIs (THI)",
"1145":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 11. Thread Pools (TPS)",
"1146":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 12. Thread-Safety Miscellaneous (TSM)",
"1147":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 13. Input Output (FIO)",
"1148":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 14. Serialization (SER)",
"1149":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 15. Platform Security (SEC)",
"1150":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 16. Runtime Environment (ENV)",
"1151":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 17. Java Native Interface (JNI)",
"1152":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 49. Miscellaneous (MSC)",
"1153":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 50. Android (DRD)",
"1154":"CWE VIEW: Weaknesses Addressed by the SEI CERT C Coding Standard",
"1155":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 01. Preprocessor (PRE)",
"1156":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 02. Declarations and Initialization (DCL)",
"1157":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 03. Expressions (EXP)",
"1158":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 04. Integers (INT)",
"1159":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 05. Floating Point (FLP)",
"1160":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 06. Arrays (ARR)",
"1161":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 07. Characters and Strings (STR)",
"1162":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 08. Memory Management (MEM)",
"1163":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 09. Input Output (FIO)",
"1164":"CWE-1164: Irrelevant Code",
"1165":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 10. Environment (ENV)",
"1166":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 11. Signals (SIG)",
"1167":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 12. Error Handling (ERR)",
"1168":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 13. Application Programming Interfaces (API)",
"1169":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 14. Concurrency (CON)",
"1170":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 48. Miscellaneous (MSC)",
"1171":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 50. POSIX (POS)",
"1172":"CWE CATEGORY: SEI CERT C Coding Standard - Guidelines 51. Microsoft Windows (WIN) ",
"1173":"CWE-1173: Improper Use of Validation Framework",
"1174":"CWE-1174: ASP.NET Misconfiguration: Improper Model Validation",
"1175":"CWE CATEGORY: SEI CERT Oracle Secure Coding Standard for Java - Guidelines 18. Concurrency (CON)",
"1176":"CWE-1176: Inefficient CPU Computation",
"1177":"CWE-1177: Use of Prohibited Code",
"1178":"CWE VIEW: Weaknesses Addressed by the SEI CERT Perl Coding Standard",
"1179":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 01. Input Validation and Data Sanitization (IDS)",
"1180":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 02. Declarations and Initialization (DCL)",
"1181":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 03. Expressions (EXP)",
"1182":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 04. Integers (INT)",
"1183":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 05. Strings (STR)",
"1184":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 06. Object-Oriented Programming (OOP)",
"1185":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 07. File Input and Output (FIO)",
"1186":"CWE CATEGORY: SEI CERT Perl Coding Standard - Guidelines 50. Miscellaneous (MSC)",
"1187":"CWE-1187: Use of Uninitialized Resource",
"1188":"CWE-1188: Insecure Default Initialization of Resource",
"2000":"CWE VIEW: Comprehensive CWE Dictionary"}